# Generated by Django 5.0.4 on 2024-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to the Patient Commitment, the Consent to Release Personal Health Information, and the Cancellation Conditions'),
        ),
        migrations.AddField(
            model_name='contact',
            name='appointment_date',
            field=models.DateField(default='2000-01-01', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='2000-01-01', verbose_name='Date (dd/mm/yyyy)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='doctor_info',
            field=models.CharField(default='Dr. Farrell, 123 Hillview St, Oshawa, R1X 3D4', max_length=200, verbose_name='Family Doctor Information'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_telephone',
            field=models.CharField(default='', max_length=20, verbose_name='Home Telephone No.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='signature',
            field=models.CharField(default='', max_length=100, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_telephone',
            field=models.CharField(default='', max_length=20, verbose_name='Work Telephone No.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='apartment_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Apartment #'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city_town',
            field=models.CharField(default='', max_length=100, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', verbose_name='Date of Birth (dd/mm/yyyy)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='health_number',
            field=models.CharField(default='', max_length=100, verbose_name='Health Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_address',
            field=models.CharField(default='', max_length=100, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(default='', max_length=100, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='residence_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Residence Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='residence_address_same_as_mailing',
            field=models.BooleanField(default=False, verbose_name='Residence Address same as mailing address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='second_name',
            field=models.CharField(default='', max_length=100, verbose_name='Second Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='send_notices_by',
            field=models.CharField(choices=[('regular_mail', 'Regular Mail'), ('email', 'Email')], default='regular_mail', max_length=20, verbose_name="Send notices from my family doctor's office to me by"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street_info',
            field=models.CharField(default='', max_length=100, verbose_name='Street No. and Name or P.O. Box, Rural Route, General Delivery'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='version_code',
            field=models.CharField(default='', max_length=100, verbose_name='Version Code'),
        ),
    ]
